[package]
name = "ame_parser"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
readme.workspace = true

[dependencies]
ame_lexer = { path = "../ame_lexer" }
ame_ast = { path = "../ame_ast" }
